[project]
name = "living_planet_eco_evo_data_uvr"
r_version = "4.6.1"

[dependencies]
birdnetR = "*"
dplyr = "*"
ggplot2 = "*"
janitor = "*"
patchwork = "*"
rcartocolor = "*"
rpart = "*"
seewave = "*"
sf = "*"
soundecology = "*"
terra = "*"
tuneR = "*"

[dev-dependencies]
IRkernel = "*"
languageserver = "*"

[activate]
prompt = true
